
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/share/apps/cmake/3.26/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Linux - 5.14.0-503.26.1.el9_5.x86_64 - x86_64
...
